- src/constants/index.js
- src/routes/WorkItems/components/Solutions/FinalSurvey/index.jsx
- src/routes/WorkItems/components/Solutions/FinalSurvey/styles.module.scss
- src/routes/WorkItems/components/Solutions/index.jsx
- src/routes/WorkItems/components/Summary/TimelineBar/Label/index.jsx
- src/routes/WorkItems/components/Summary/TimelineBar/Label/styles.module.scss
- src/routes/WorkItems/components/Summary/TimelineBar/Point/index.jsx
- src/routes/WorkItems/components/Summary/TimelineBar/Point/styles.module.scss
- src/routes/WorkItems/components/Summary/TimelineBar/Track/index.jsx
- src/routes/WorkItems/components/Summary/TimelineBar/Track/styles.module.scss
- src/routes/WorkItems/components/Summary/TimelineBar/index.jsx
- src/routes/WorkItems/components/Summary/TimelineBar/styles.module.scss
- src/routes/WorkItems/components/Summary/TimelineHeader/index.jsx
- src/routes/WorkItems/components/Summary/index.jsx
- src/routes/WorkItems/index.jsx
- src/routes/WorkItems/styles.module.scss
- src/services/work.js
- src/utils/index.js
- src/utils/work.js
1. fixed 'days to begin' of Draft/Submitted
2. fixed format of date as MM/DD/YYYY
3. fixed DOWNLOADS READY and MARK AS DONE as hyper-links
4. fixed
---
1. fixed format of 'days to begin', ex: 02 DAYS, 01 DAY, DUE NOW, LATE BY 01 DAY, LATE BY 02 DAYS
2. fixed stylesheet: 'work name' font-size = 20px, 'next action' font weight = 600, timeline width = 888px - 16px * 2 (at screen width 1440px), timeline date format MM/DD/YYYY
3. fixed for Feedback modal (opening data will be the same as the last closed) 
---
> final minor fixes

- src-ts/lib/styles/_modals.scss
Fixed jumps on the modal after opening.
> PROD-1638_final_tweaks_for_account - PROD-1558-profile

- src-ts/config/environments/environment.default.config.ts
- src-ts/config/environments/environment.prod.config.ts
- src-ts/declarations.d.ts
- src-ts/lib/button/Button.tsx
- src-ts/lib/functions/component-visible-functions/component-visible.functions.tsx
- src-ts/lib/functions/component-visible-functions/index.ts
- src-ts/lib/functions/index.ts
- src-ts/lib/functions/message-functions/index.ts
- src-ts/lib/functions/message-functions/message-store/get-unread-message-count-response.model.ts
- src-ts/lib/functions/message-functions/message-store/index.ts
- src-ts/lib/functions/message-functions/message-store/message.store.ts
- src-ts/lib/functions/message-functions/message.functions.ts
- src-ts/lib/global-config.model.ts
- src-ts/lib/table/Table.tsx
- src-ts/lib/table/table-column.model.ts
- src-ts/lib/tooltip/Tooltip.module.scss
- src-ts/lib/tooltip/Tooltip.tsx
- src-ts/lib/tooltip/index.ts
- src-ts/lib/work-provider/work-functions/work-factory/work-type.enum.ts
- src-ts/lib/work-provider/work-functions/work.functions.ts
- src-ts/tools/work/work-table.config.tsx
https://topcoder.atlassian.net/browse/PROD-1626
- add unread message counts to list (NOTE: none of the users i have access to have unread messages--need to determine how to create them)
- add message column header tooltip
> PROD-1626 messages - PROD-1521_work-home

- src-ts/lib/functions/message-functions/message.functions.ts
- src-ts/lib/work-provider/work-functions/work-factory/work-type.enum.ts
- src-ts/lib/work-provider/work-functions/work-factory/work.factory.ts
- src-ts/lib/work-provider/work-functions/work-factory/work.model.ts
- src-ts/lib/work-provider/work-functions/work-store/challenge.model.ts
- src-ts/lib/work-provider/work-functions/work.functions.ts
https://topcoder.atlassian.net/browse/PROD-1625
- filters non-self-service challenges from results table
- adds costs to table
> PROD-1625 work costs - PROD-1521_work-home

- src-ts/lib/styles/_buttons.scss
- src-ts/lib/table/Table.module.scss
- src-ts/lib/table/Table.tsx
- src-ts/lib/table/table-cell/TableCell.module.scss
- src-ts/lib/table/table-cell/TableCell.tsx
- src/components/PageHeader/index.jsx
https://topcoder.atlassian.net/browse/PROD-1758
- fix style of the Start Work button in the header to match the new design system
- fix the row hover styling so that it doesn't prevent the delete button from being clicked
- add padding to the delete button so it's a larger target
- add background color to the delete button on hover so it's easier to see
> PROD-1758 Work Dashboard Delete Button Fixes - PROD-1521_work-home

- src-ts/lib/content-layout/ContentLayout.module.scss
- src-ts/lib/content-layout/ContentLayout.tsx
- src-ts/lib/content-layout/index.ts
- src-ts/lib/form/Form.module.scss
- src-ts/lib/form/Form.test.tsx
- src-ts/lib/form/Form.tsx
- src-ts/lib/form/form-inputs/form-input/input-text/InputText.module.scss
- src-ts/lib/form/form-inputs/form-input/input-wrapper/InputWrapper.module.scss
- src-ts/lib/form/validator-functions/validator.functions.ts
- src-ts/lib/index.ts
- src-ts/lib/styles/_buttons.scss
- src-ts/lib/styles/_layout.scss
- src-ts/lib/styles/_modals.scss
- src-ts/lib/styles/_typography.scss
- src-ts/utils/account/Account.module.scss
- src-ts/utils/account/Account.tsx
- src-ts/utils/account/change-password/change-password-form.config.ts
https://topcoder.atlassian.net/browse/PROD-1777
- change button on pw label to change pw
- change pw error to 8+
- api error above error
- make padding around the page header equal above and below
- set max width of page content to 1440px
- fix input placeholder color
- fix modal close button focus style
> PROD-1777 Account Demo Feedback - PROD-1558_profile

- src-ts/lib/form/form-functions/form.functions.ts
- src-ts/lib/form/form-input.model.ts
- src-ts/lib/form/validator-functions/validator.functions.ts
- src-ts/utils/account/change-password/change-password-form.config.ts
- src-ts/utils/account/edit-name/edit-name-form.config.ts
validation on pw form; #time 30m
> PROD-1777 validation fixes - PROD-1558_profile

- src-ts/lib/button/index.ts
- src-ts/lib/content-layout/ContentLayout.module.scss
- src-ts/lib/content-layout/ContentLayout.tsx
- src-ts/tools/work/WorkTable.tsx
- src-ts/tools/work/work-table.config.tsx
- src/routes/MyWork/components/Dashboard/index.jsx
- src/routes/MyWork/index.jsx
https://topcoder.atlassian.net/browse/PROD-1782
this uses the content layout for the work table so that it has the same header as the account settings
> PROD-1782 header component - PROD-1521_work-home

- src-ts/lib/content-layout/ContentLayout.module.scss
- src-ts/lib/table/Table.module.scss
- src-ts/lib/table/Table.tsx
Ticket https://topcoder.atlassian.net/browse/PROD-1795
- align table to the left
- add scrollbar for table on smaller widths
> PROD-1795 - Align Table overflow at smaller widths

- src/routes/BasicInfo/index.jsx
- src/routes/Products/DataExploration/Routes/BasicInfo/index.jsx
This change was made outside of the Platform MVP epic, so I am not sure if there is a ticket. I couldn't find one. 
Here's the original PR: https://github.com/topcoder-platform/mfe-customer-work/pull/232/files
> redo changes to fix product routes -> develop

- src/components/Breadcrumb/index.jsx
- src/components/Breadcrumb/style.scss
- src/components/Layout/index.jsx
- src/components/Layout/styles.module.scss
- src/routes/SelectWorkType/index.jsx
- src/styles/_include.scss
- src/styles/_typography.scss
- src/styles/_variables.scss
This adds the breadcrumb to the Select Work Type page: https://topcoder.atlassian.net/browse/PROD-1559
Original PR: https://github.com/topcoder-platform/mfe-customer-work/pull/233/files
mfe-core = master
mfe-header = master
> PROD-1559 breadcrumb redo -> develop

- src-ts/config/environments/environment.config.ts
> PROD-1840 add logging for env config -> develop

- config/dev.js
- config/index.js
- config/local.js
- config/prod.js
cleans up the last of the debug code
> PROD-1840 logging/config -> develop

- src-ts/config/environments/environment.config.ts
- src-ts/config/environments/environment.default.config.ts
- start-bsouza.sh
https://topcoder.atlassian.net/browse/PROD-1844
- use APPENV to define environment config
- change logging service to mfe-customer-work
Logs: https://app.datadoghq.com/logs?live=true
mfe-core = master
mfe-header = master
> PROD-1844 logging and environment config improvements -> develop

- src-ts/lib/table/Table.module.scss
- src-ts/lib/table/Table.tsx
- src-ts/lib/table/table-cell/TableCell.module.scss
- src-ts/lib/tooltip/Tooltip.tsx
https://topcoder.atlassian.net/browse/PROD-1854
- align right-aligned column headers to right
- align date columns to the left
mfe-core = master
mfe-header = master
> PROD-1854 dashboard demo feedback -> PROD-1521_work-home

- src-ts/lib/index.ts
- src-ts/lib/loading-spinner/LoadingSpinner.module.scss
- src-ts/lib/loading-spinner/LoadingSpinner.tsx
- src-ts/lib/loading-spinner/index.ts
- src-ts/tools/work/work-table/WorkTable.tsx
https://topcoder.atlassian.net/browse/PROD-1858
This PR handles 
- Add Loading spinner to Work Table until work is loaded
> PROD-1858 - Add Loading spinner to Work Table

- src-ts/tools/work/work-detail-summary/WorkDetailSummary.tsx
- src-ts/tools/work/work-detail-summary/WorkTransferredStatus/WorkTransferredStatus.module.scss
- src-ts/tools/work/work-detail-summary/WorkTransferredStatus/WorkTransferredStatus.tsx
- src-ts/tools/work/work-detail-summary/WorkTransferredStatus/index.ts
- src/routes/WorkItems/index.jsx
https://topcoder.atlassian.net/browse/PROD-1849
Added transferred state in work item's details summary
> PROD-1849 - Create Transferred Summary

- src-ts/lib/content-layout/ContentLayout.module.scss
- src-ts/lib/loading-spinner/LoadingSpinner.module.scss
- src-ts/tools/work/work-table/WorkTable.module.scss
- src-ts/tools/work/work-table/WorkTable.tsx
https://github.com/topcoder-platform/mfe-customer-work/pull/290#discussion_r867020505
> PROD-1858 - Make loading spinner take whole page content height

- src/components/Button/index.jsx
- src/components/FormElements/FormField/index.jsx
- src/components/FormElements/FormInputText/index.jsx
- src/components/FormElements/FormInputTextArea/index.jsx
- src/components/Modal/SupportModal.jsx
- src/components/Modal/index.jsx
- src/components/ReactSelect/index.jsx
- src/routes/Payment/components/PaymentForm/index.jsx
- src/routes/Review/components/PaymentForm/index.jsx
https://github.com/topcoder-platform/mfe-customer-work/issues/74
> fix issue 74

- src-ts/header/logo/Logo.tsx
- src-ts/header/tool-selectors/tool-selectors-wide/tool-selector-wide/ToolSelectorWide.module.scss
- src-ts/header/tool-selectors/tool-selectors-wide/tool-selector-wide/ToolSelectorWide.tsx
- src-ts/lib/route-provider/route.utils.ts
- src-ts/lib/styles/_buttons.scss
- src-ts/tools/work/Work.tsx
https://topcoder.atlassian.net/browse/PROD-1551?focusedCommentId=19365
- show ability to click header links when not on home page
- redirect back to logged out home page from dashboard when not logged in
- remove outline from focused button with tertiary style
> PROD-1868 Header Fixes from QA -> PROD-1521_PROD-1551_dashboard-and-header

- src-ts/lib/styles/_typography.scss
- src-ts/tools/work/work-table/work-table-title-renderer/WorkTableTitleRenderer.module.scss
- src-ts/tools/work/work-table/work-table-title-renderer/WorkTableTitleRenderer.tsx
https://topcoder.atlassian.net/browse/PROD-1873
- Handle Project Title Overflow in the work items table
> PROD-1873 - Handle Project Title Overflow

- src/IntakeForm.jsx
https://topcoder.atlassian.net/browse/PROD-1929
> PROD-1521 PROD-1551 Remove Unread Messages from Dashboard -> develop

- src-ts/lib/page-footer/PageFooter.tsx
Removes the See a Bug? link in the footer. This will be added later in [PROD-1864](https://topcoder.atlassian.net/browse/PROD-1864).
> PROD-1529 remove see a bug from footer -> PROD-1529_page-footer

- src/routes/WorkItems/components/Solutions/SolutionListItem/index.jsx
- src/routes/WorkItems/components/Solutions/SolutionListItem/styles.module.scss
- src/routes/WorkItems/components/Solutions/index.jsx
- src/routes/WorkItems/components/Solutions/styles.module.scss
- src/routes/WorkItems/index.jsx
- src/routes/WorkItems/styles.module.scss
- src/styles/_variables.scss
https://topcoder.atlassian.net/browse/PROD-1526
style workd details > solutions table according to figma.
> PROD-1526 - style workd details / solutions table

- src-ts/lib/button/Button.tsx
- src-ts/lib/form/Form.tsx
- src-ts/lib/form/form-inputs/form-input-row/FormInputRow.module.scss
- src-ts/lib/form/form-inputs/form-input/input-rating/InputRating.module.scss
- src-ts/lib/form/form-inputs/form-input/input-rating/InputRating.tsx
- src-ts/lib/form/form-inputs/form-input/input-wrapper/InputWrapper.module.scss
- src-ts/lib/form/form-inputs/form-input/input-wrapper/InputWrapper.tsx
- src-ts/lib/styles/_buttons.scss
- src-ts/lib/styles/_typography.scss
- src-ts/lib/tooltip/Tooltip.tsx
- src-ts/tools/work/work-detail-header/WorkFeedback/WorkFeedback.module.scss
- src-ts/tools/work/work-detail-header/WorkFeedback/WorkFeedback.tsx
[PROD-1877](https://topcoder.atlassian.net/browse/PROD-1877)
- fix stars tooltip
- fix hover issue in mark as done modal
- update styling for mark as done modal
to make the button "mark as done" visible please commend this in WorkDetailHeader.tsx:
> Prod 1877 mark as done modal issues

- src-ts/lib/work-provider/work-functions/work-factory/work-type.enum.ts
- src-ts/lib/work-provider/work-functions/work-factory/work.factory.ts
https://topcoder.atlassian.net/browse/PROD-1937
Adds the new work type, find me data, to the work dashboard.
> PROD-1937 add Find Me Data -> PROD_1521_PROD-1551_dashboard-and-filter

- src-ts/tools/work/work-table/work-status-renderer/WorkStatusRenderer.module.scss
This PR adds the Find Me Data to the home dashboard.
> PROD-1521 PROD-1551 find me data on table -> develop

- src-ts/lib/tabs-navbar/TabsNavbar.module.scss
https://topcoder.atlassian.net/browse/PROD-1944
Prototype figma: https://www.figma.com/proto/2t8Wcyu8FAXxzQGpyK8r4f/TC-Design-System-2.0-%2F-2022?page-id=783%3A9377&node-id=783%3A9378&viewport=318%2C48%2C1.28&scaling=min-zoom
- added Hover Effect on Tabs navbar
> PROD-1944 - Add Hover Effect on Tabs navbar

- src/constants/index.js
- src/routes/Branding/components/ColorOptions/index.jsx
- src/routes/Products/components/BasicInfoForm/index.jsx
improvement(reskin) : qa part 1 f2f
> WIP: Reskin For Checking Code Changes

- src-ts/lib/table/Table.tsx
- src-ts/lib/table/table-column.model.ts
- src-ts/lib/table/table-functions/index.ts
- src-ts/lib/table/table-functions/table.functions.ts
- src-ts/lib/table/table-sort/TableSort.tsx
- src-ts/tools/work/work-table/WorkTable.tsx
- src-ts/tools/work/work-table/work-table.config.tsx
https://topcoder.atlassian.net/browse/PROD-2013
If column X is sorted in one direction, then column Y is sorted, then column X is sorted again, the 2nd sort of column X will sort by its default direction again.
mfe-core = dev
mfe-header = dev
> PROD-2013 default sort direction for columns

- src-ts/lib/styles/variables/_palette.scss
- src-ts/lib/tabs-navbar/TabsNavbar.module.scss
https://topcoder.atlassian.net/browse/PROD-2012
mfe-core = dev
mfe-header = dev
> PROD-2012 Tab Navbar Color Updates -> PROD-1516_work-filter

- src-ts/tools/work/work-table/WorkTable.tsx
https://topcoder.atlassian.net/browse/PROD-2016
> PROD-2016 fix bug where table doesn't refresh after deletion -> PROD-1516_work-filter

- src-ts/lib/portal/Portal.tsx
- src-ts/lib/tooltip/Tooltip.module.scss
- src-ts/lib/tooltip/Tooltip.tsx
https://topcoder.atlassian.net/browse/PROD-2017
Delete Button Hover Shakes Draft Page
> PROD-2017 - update tooltip initial positioning

- src-ts/header/tool-selectors/tool-selectors-narrow/tool-selector-narrow/ToolSelectorNarrow.tsx
- src-ts/header/tool-selectors/tool-selectors-wide/tool-selector-wide/ToolSelectorWide.tsx
- src-ts/lib/functions/authentication-functions/authentication-url.config.ts
- src-ts/lib/route-provider/route.utils.ts
- src-ts/tools/work/Work.tsx
- src-ts/tools/work/work-table/WorkTable.tsx
This is a refactor for the tools nav. No functionality changes.
> PROD-2014 fix tools nav so that it can support new tools -> PROD-1516_work-filter

- src-ts/lib/work-provider/work-functions/work-factory/work-type.enum.ts
- src-ts/lib/work-provider/work-functions/work-factory/work.factory.ts
https://topcoder.atlassian.net/browse/PROD-1531
> PROD-1999 add support for Problem statement work on the dashboard -> develop

- src-ts/lib/tabs-navbar/TabsNavbar.module.scss
https://topcoder.atlassian.net/browse/PROD-2019 
Fix the height for the active element in the tabs navbar when screen is smaller width.
> PROD-2019 - fix tabs navbar active item height

- src-ts/lib/modals/terms-modal/TermsModal.tsx
https://topcoder.atlassian.net/browse/PROD-1529
This fixes the URL in the terms modal
mfe-core & mfe-header = qa
> PROD-2067 footer issues -> QA

- src/constants/index.js
- src/routes/Products/components/BasicInfoForm/index.jsx
- Removed extra question mark after "What will I receive?" header
- Fixed wording of headings in expandable sections
> PROD-1986 DA basic info bugs -> PROD-1982 DA bugs

- package-lock.json
- src-ts/lib/work-provider/work.provider.tsx
- src/IntakeForm.jsx
Note: I could only reproduce this bug with Data Advisory work items, not Web
- Added missing route for data advisory work intakes
> PROD-2071 clicking on draft redirects to home page -> PROD-1896 website intake bugs

- src-ts/header/tool-selectors/tool-selectors-narrow/ToolSelectorsNarrow.tsx
- src-ts/header/tool-selectors/tool-selectors-wide/ToolSelectorsWide.tsx
- src-ts/lib/route-provider/route-context-data.model.ts
- src-ts/lib/route-provider/route.context.tsx
- src-ts/lib/route-provider/route.provider.tsx
https://topcoder.atlassian.net/browse/PROD-2086
This removes hidden routes from the tools hamburger menu in mobile view
mfe-core & mfe-header = qa branch
plz approve/merge/delete
> PROD-2086 remove obsolete url from mobile hamburger nav-> qa

- src-ts/tools/work/work-detail-details/work-detail-details-pane/WorkDetailDetailsPane.tsx
- src/routes/Products/components/BasicInfo/index.jsx
- src/routes/Products/components/BasicInfoForm/index.jsx
- src/routes/Review/components/ReviewTable/index.jsx
- There was a bug where the name of the FMD work items was not getting displayed correctly in the My Work lists due to the name for these work item types being stored in a separate variable specific to FMD
- This PR removes that variable findMeProjectTitle altogether, and instead uses the same variable used for the other work types
> PROD-2096 incorrect title displayed -> PROD-120 find me data

- src/routes/BasicInfo/styles.module.scss
- src/routes/Branding/styles.module.scss
- src/routes/LoginPrompt/styles.module.scss
- src/routes/PageDetails/styles.module.scss
- src/routes/Products/components/BasicInfo/styles.module.scss
- src/routes/Review/styles.module.scss
- src/routes/WebsitePurpose/styles.module.scss
- src/styles/_mixins.scss
- Fixed back button icon(aligned the chevron to the center)
This PR also fixes them in other flows.
> PROD-2124 center align icon in back button -> PROD 120 FMD

- .circleci/config.yml
- package-lock.json
https://topcoder.atlassian.net/browse/PROD-2153
Try to use nvm in the build to eliminate changes to the package-lock file
> PROD-2153 add nvm install/use -> PROD-120_find-me-data

- src/routes/Review/components/PaymentForm/index.jsx
- src/routes/Review/components/PaymentForm/styles.module.scss
- src/routes/Review/index.jsx
- src/routes/Review/styles.module.scss
- Moved terms and conditions checkbox before the notes section
> PROD-2104 moved checkbox before the notes section -> PROD-120 FMD

- src/routes/Review/components/PaymentForm/styles.module.scss
What's in this PR?
- fixed the margin bottom for mobile resolution.
> PROD 2104 mobile resolution fix -> PROD 120 FMD
